# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 11:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=63)),
                ('description', models.CharField(max_length=255)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_in_seconds', models.PositiveIntegerField()),
                ('standardGame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game', to='games.Game')),
            ],
        ),
    ]
