# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='type',
            field=models.CharField(choices=[('STAND', 'Standard'), ('END', 'Endless'), ('WHACK', 'Whack-a-mole')], default='STAND', max_length=12),
        ),
    ]
