# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 11:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_game_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='standardGame',
            new_name='game',
        ),
    ]
