# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_auto_20171101_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='difficulty',
            field=models.CharField(choices=[('Simple', 'Simple'), ('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard'), ('Extreme', 'Extreme')], default='Simple', max_length=7),
        ),
        migrations.AlterField(
            model_name='game',
            name='type',
            field=models.CharField(choices=[('Standard', 'standard'), ('Endless', 'endless'), ('Whack-a-mole', 'whack-a-mole')], default='Standard', max_length=12),
        ),
    ]
