# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20171101_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='difficulty',
            field=models.CharField(choices=[('simple', 'Simple'), ('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('extreme', 'Extreme')], default='simple', max_length=7),
        ),
        migrations.AlterField(
            model_name='game',
            name='type',
            field=models.CharField(choices=[('standard', 'Standard'), ('endless', 'Endless'), ('whack-a-mole', 'Whack-a-mole')], default='standard', max_length=12),
        ),
    ]
