# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 19:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_auto_20171101_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_in_seconds', models.PositiveIntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='games.Game')),
            ],
        ),
        migrations.RemoveField(
            model_name='record',
            name='game',
        ),
        migrations.DeleteModel(
            name='Record',
        ),
    ]
