# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_auto_20171102_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='errors',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='words_per_minute',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='difficulty',
            field=models.CharField(choices=[('simple', 'simple'), ('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard'), ('extreme', 'extreme')], default='simple', max_length=7),
        ),
        migrations.AlterField(
            model_name='game',
            name='type',
            field=models.CharField(choices=[('standard', 'standard'), ('endless', 'endless'), ('whack-a-mole', 'whack-a-mole')], default='standard', max_length=12),
        ),
    ]
