# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-26 13:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('time_limit_seconds', models.PositiveIntegerField()),
                ('difficulty', models.CharField(choices=[('SMP', 'Simple'), ('ESY', 'Easy'), ('MDM', 'Medium'), ('HRD', 'Hard'), ('EXE', 'Extreme')], max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_time_seconds', models.PositiveIntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game', to='games.Game')),
            ],
        ),
    ]
